apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: myproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kemoury/mkbackend
        ports:
        - containerPort: 8080
