apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa  # AJOUTÉ
      containers:
      - name: backend
        image: kemoury/backend:v3
        ports:
        - containerPort: 8080
        # AJOUTÉ: Variables d'environnement
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: ADMIN_TOKEN
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: ADMIN_PASSWORD
        # AJOUTÉ: Health checks
        readinessProbe:
          httpGet:
            path: /joueurs
            port: 8080
          initialDelaySeconds: 45  # Augmenté
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3 

        livenessProbe:
          httpGet:
            path: /joueurs
            port: 8080
          initialDelaySeconds: 90  # Augmenté
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3