# Secrets sécurisés pour remplacer les variables d'environnement en dur
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tournoi-app
type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWU=  # base64 de "username"
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # base64 de "mypassword" 
  POSTGRES_DB: dG91cm5hbWVudF9kYg==  # base64 de "tournament_db"